routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('articles', 'ArticleController');
    Route::post('articles/{article}/{comment?}', 'ArticleController@storeComment')->name('articles.create.comment');
    Route::get('/my/friends','FriendController@index')->name('friends');
    Route::get('/request/friends','FriendController@request')->name('request.friends');
    Route::get('/user/{user}','FriendController@show')->name('user.show');

    Route::post('/friends/{user}','FriendController@store')->name('friends.request');
    Route::post('/friend/{friend}/{action}','FriendController@update')->name('friends.response');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model{
    protected $perPage=20;

    protected $guarded=[''];
    public function tags(){
        return $this->belongsToMany(Tag::class,'article_tag','article_id', 'tag_id')
        ->withTimestamps()
        ->using(ArticleTag::class)
        ; }
    public function comments(){ return $this->morphMany(Comment::class ,'commentable'); }

    protected static function boot(){
        parent::boot();
        static::creating(function ($article) {
            $article->user_id= $article->user_id ??  auth()->id();
        });
        static::deleting(function ($article) {
            $article->tags()->delete();
            $article->comments()->delete();
        });
    }

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Comment;
use App\Tag;
use foo\bar;
use Illuminate\Http\Request;

class ArticleController extends Controller{

    public function index(){
        $articles=Article::paginate();
        return view('article.index',[
            'articles'=>$articles
        ]);
    }

    public function create(){
        return  view('article.create');
    }

    public function store(Request $request){
        $validated=$request->validate([
            'title'=>['required','min:3'],
            'body'=>['required'],
            'tags'=>['required','array'],
        ]);
        $tags=[];
        foreach ($validated['tags'] as $tag) $tags[]=Tag::firstOrCreate(['name'=>$tag])->id;
//        dd($tags);
        unset($validated['tags']);
        $article=Article::create($validated);

        $article->tags()->sync($tags);

        return back();
    }

    public function storeComment(Article $article,Comment $comment,Request $request){
        $validated=$request->validate([ 'comment'=>['required'] ]);
        if (!$comment->id){
            $article->comments()->create($validated);
        }else{
            $comment->childs()->create([
                'comment'=>$validated['comment'],
                'commentable_type'=>$comment->commentable_type,
                'commentable_id'=>$comment->commentable_id,
            ]);
        }
        return back();
    }

    public function show(Article $article){

        return view('article.show',compact('article'));
    }

    public function edit(Article $article){

        return view('article.edit',compact('article'));
    }
    public function update(Request $request, Article $article){
        $validated=$request->validate([
            'title'=>['sometimes','min:3'],
            'body'=>['sometimes'],
            'tags'=>['sometimes','array'],
        ]);
        if (count($validated)>0){
            $article->update($validated);
            if (count($validated['tags'])>0){
                $tags=[];
                foreach ($validated['tags'] as $tag) $tags[]=Tag::firstOrCreate(['name'=>$tag])->id;
                $article->tags()->sync($tags);
            }
        }
        return back();
    }

    public function destroy(Article $article){
       $article->delete();

        return  back();
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Article</div>

                <div class="card-body">
                    <form method="post" action="{{route('articles.store')}}">
                        @csrf
                        <div class="form-group">
                            <label for="title">title</label>
                            <input type="text"
                                   class="form-control" name="title" id="title" aria-describedby="helpId" placeholder="title">
                            @error('title')
                            <small id="helpId" class="form-text text-muted">{{$message}}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="body">body</label>
                            <textarea type="text"
                                   class="form-control" name="body" id="body" aria-describedby="helpId" placeholder="body"></textarea>
                            @error('body')
                            <small id="helpId" class="form-text text-muted">{{$message}}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="tags">tags</label>
                            <input type="text" class="form-control mt-2" name="tags[]" id="tags" aria-describedby="helpId" placeholder="">
                            <input type="text" class="form-control mt-2" name="tags[]" id="tags" aria-describedby="helpId" placeholder="">
                            @error('tags')
                            <small id="helpId" class="form-text text-muted">{{$message}}</small>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/article/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @foreach ($articles as $article)
            <div class="col-md-8 mb-2">
                <div class="card">
                    <div class="card-header"><a href="{{route('articles.show',$article)}}">{{ $article->title }}</a></div>
                    <div class="card-body">
                        {!! $article->body !!}
                    </div>
                </div>
            </div>
        @endforeach
       <div class="col-md-12">
           {{$articles->links()}}
       </div>
    </div>
</div>
@endsection

resources/views/article/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{$article->title}}</div>

                <div class="card-body">
                    {!! $article->body!!}
                </div>
            </div>
            <div class="card mt-2">
                <div class="card-body">
                    <h4 class="card-title">comment</h4>
                    @auth
                    <form method="post" action="{{route('articles.create.comment',$article)}}">
                        @csrf
                        <div class="form-group">
                            <label for=""></label>
                            <textarea class="form-control" name="comment" id="" rows="3"></textarea>
                            @error('comment')
                                <p class="text-danger">
                                    {{$message}}
                                </p>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">comment</button>
                    </form>
                    @else
                        <div class="alert alert-info" role="alert">
                            <strong>you need to login</strong>
                        </div>
                    @endauth
                </div>
            </div>
        </div>
        @foreach ($comments=$article->comments()->whereNull('comment_id')->paginate() as $comment)
            <div class="col-md-8 mt-3">
                <div class="card">
                    <div class="card-header">{{$comment->user->name}}</div>

                    <div class="card-body">
                        {!! $comment->comment !!}
                        <hr>
                        <ul>
                        @foreach ($comment->childs as $child)
                            <li>{{$child->comment}}</li>
                        @endforeach
                        </ul>
                    </div>
                </div>
                @auth
                <div class="card mt-2">
                    <div class="card-body">
                        <h4 class="card-title">Reply</h4>
                        <form method="post" action="{{route('articles.create.comment',['article'=>$article,'comment'=>$comment])}}">
                            @csrf
                            <div class="form-group">
                                <label for=""></label>
                                <textarea class="form-control" name="comment" id="" rows="3"></textarea>
                                @error('comment')
                                <p class="text-danger">
                                    {{$message}}
                                </p>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary">Reply</button>
                        </form>
                    </div>
                </div>
                @else
                    <div class="alert alert-info" role="alert">
                        <strong>you need to login</strong>
                    </div>
                @endauth
            </div>
        @endforeach
        <div class="col-md-12">
            {{$comments->links()}}
        </div>

    </div>
</div>
@endsection